### ISSUE TITLE
Using submitit without slurm

### ISSUE THREAD

**Issue by achalddave** [facebookincubator/submitit#1599]
I'd like to use submitit on a cluster that doesn't use slurm. That is, I'd like to use submitit's functionality for pickling the python environment and submitting a function to run on another machine, but specify the nodes manually rather than using the slurm scheduler. A few questions:
1. Is this currently supported? (I believe not)
2. Is this a reasonable thing to do? Or are there better alternatives to submitit for this use case?
3. Is the right way to do this to write an `SshExecutor` to replace the `SlurmExecutor`? If so, are there any pitfalls I should be concerned about if I try to implement this?

Thanks!

**Comment by jrapin** [comment]
Hi @achalddave 

> Is this currently supported?

no

> Is this a reasonable thing to do?

If it makes your life easier, it could be, although it will probably take some time to get it right

>  Or are there better alternatives to submitit for this use case?

I would recommend having first a good look at [dask.distributed](https://distributed.dask.org/en/latest/) if they have anything available that could suit your need, they have similar executor APIs for a lot of use cases.

> Is the right way to do this to write an SshExecutor to replace the SlurmExecutor?

Yes. There is a plugin/discovery system so you can actually implement it in different packages and it could get discovered by submitit (cc @gwenzek who knows more about it). Whether your executor would be a good fit for including within `submitit` package directly would depend on how general you want to make it.

>  If so, are there any pitfalls I should be concerned about if I try to implement this?

For now we have only implemented such executors when there was a server running which would provide information about the jobs (eg: status etc), and the filesystem (or part of it) was shared. So basically we had easy ways to communicate with the jobs. Doing so through ssh will probably be much more cumbersome

**Comment by achalddave** [comment]
Thanks for the information! Fair enough, from a brief look at LocalExecutor and SlurmExecutor, it seems writing an SshExecutor is not entirely trivial, so I'll take a closer look at dask.distributed.
