### ISSUE TITLE
Add qos parameter to Slurm Executor

### ISSUE THREAD

**Issue by ondrejtichacek** [facebookincubator/submitit#1610]
Slurm implements a Quality of Service (QOS), see https://slurm.schedmd.com/qos.html
that is used in our cluster to prioritize jobs and groups of users. Some partitions also require specific QOS.

It would be great if submitit could include the QOS option in the generated sbatch script.

I assume this would only require modifying the `_make_sbatch_string` function in `slurm.py`
```
qos: tp.Optional[str] = None,
```
and the documentation.

**Comment by gwenzek** [comment]
Sounds like a good idea. As you said it seems to be a one line fix. Most of the slurm options aren't documented anyway since they are just forwarding to `srun`.

**Comment by gwenzek** [comment]
Fixed by a559304fce4a0461a8352281f4a24a55dcfe4648 following  #1614
