### ISSUE TITLE
1.3.1 version installation fails from PyPi due to requirements.

### ISSUE THREAD

**Issue by MartSlaaf** [facebookincubator/submitit#1619]
Hello!

Installation of the newest version (1.3.1) fails with error
```
FileNotFoundError: [Errno 2] No such file or directory: 'requirements/main.txt'
```

I install with command 
```
pip install submitit --upgrade
```

Although, this works perfectly:
```
pip install submitit==1.3.0 --upgrade
```

It could be replication of [this](https://github.com/facebookincubator/submitit/issues/16) issue.

**Comment by jrapin** [comment]
@gwenzek , old setuptools again then?
there does not seem anything that could have gone wrong otherwise :s 
https://github.com/facebookincubator/submitit/compare/1.3.0...master

**Comment by jrapin** [comment]
Hi @MartSlaaf 
Sorry for the delay, it's supposed to be solved now, but I still have not understood why it used to work and started failing now :s

**Comment by MartSlaaf** [comment]
Hello @jrapin,
no problems for me.
Works now, thanks!
