### ISSUE TITLE
Job arrays with more than max # jobs

### ISSUE THREAD

**Issue by sgbaird** [facebookincubator/submitit#1624]
Curious if `submitit` has any facilities for handling a list of jobs with more than the specified max # jobs? (e.g. 500). For example, automatically splitting these into separate job arrays.

For example:
```python
import submitit
from numpy.random import randint

a = randint(100, size=600)
b = randint(100, size=600)

executor = submitit.AutoExecutor(folder=log_folder)
executor.update_parameters(slurm_array_parallelism=2)
jobs = executor.map_array(add, a, b) 
```

**Comment by jrapin** [comment]
What do you call `more than the specified max # jobs`?
The code you wrote is correct, it will run 600 jobs in the array, at most 2 at a time
If you want to pack jobs together, you can also check `submitit.helpers.FunctionSequence`

**Comment by sgbaird** [comment]
Sometimes on compute clusters they limit the number of jobs in a job array. For example, only being able to submit up to 500 jobs in a single job array. I.e. `sbatch -a 1-500 ...`

**Comment by jrapin** [comment]
I did not expect there could be such limitations, I'm only using one specific cluster which does not have this. In any case, no there is no facilities for this sorry.

**Comment by gwenzek** [comment]
This sound weird, Could you ask your slurm administrator why they have such limitation ? you splitting you array in three is not gonna help the scheduler either.
If you have a good reason I'd love to hear about it.
Closing the issue in the mean time.
