### ISSUE TITLE
Context manager and log folder naming

### ISSUE THREAD

**Issue by lyndond** [facebookincubator/submitit#1631]
Using the batch context manager, I'm having trouble naming output folders according to the arguments of my for loops. Is there a way to do the following:

```
with executor.batch()
     for a in [1, 2]:
        for b in [3, 4, 5]:
            job = executor.submit(func, a, b)
```

where the output folders are formatted as: `f"/path/to/outputs/%j/a{a}-b{b}/"` instead of `.../<array job id>_<array task id>`?

I'm also open to any other suggested solution to this as well (e.g. submitting job array without using the context manager).

**Comment by jrapin** [comment]
Hi,
That's definitely not supported by submitit, the only pattern that is accepted is "%j" which you are already using.
As far as I know, that's not even possible with slurm directly, I don't see any way in specifying some custom names for each file, they must all have the same pattern.
