### ISSUE TITLE
bash script without --wckey

### ISSUE THREAD

**Issue by pritamqu** [facebookincubator/submitit#1632]
my slurm server doesn't recognize --wckey, is there a way to create bash file without wckey argument?
i tried mentioning wckey=None, in executor.update_parameters(), but it didn't work.

thanks!

**Comment by KevinMusgrave** [comment]
Not sure if related, but I was getting ```sbatch: error: Batch job submission failed: Invalid wckey specification```, and then I set wckey="" and it worked.

**Comment by pritamqu** [comment]
thanks i will check this one.

**Comment by jrapin** [comment]
Hi!
Did it work? I expect it should.
We're using this wckey internally to be able to check which jobs are launched through submitit. Sorry it makes a mess :s but that should indeed be easy to deactivate

**Comment by slerman12** [comment]
Is there a way to set wckey="" using the Hydra submitit plugin?

With Hydra, I have a config file and I just added wckey: "" to that config's launcher, but it didn't recognize the argument

**Comment by gwenzek** [comment]
I guess that's a question for Hydra submitit plugin. I don't use myself.
