### ISSUE TITLE
default timeout_min is set to 5

### ISSUE THREAD

**Issue by MinkyuHa** [facebookincubator/submitit#1633]
if no timeout_min parameter in update_parameters,
it is set to 5 min.
How to set TimeLimit=UNLIMITED ?

**Comment by jrapin** [comment]
From my understanding this option is not available in sbatch/srun. It looks like it can only be used with scontrol a posteriori, or to configure a partition, I'm not sure.
You can try setting timeout_min=0 though, it may provide the partition default duration, or just set a large number.

**Comment by gwenzek** [comment]
timeout_min=2**32 should work, but obviously we can't set this as the default value.

**Comment by polm-stability** [comment]
Why is this set by default at all? If it must be set, why isn't this more clearly documented?
