### ISSUE TITLE
Logs of slurm job failure in submitit logs

### ISSUE THREAD

**Issue by mbanani** [facebookincubator/submitit#1641]
I am facing an issue with jobs failing without a clear reason in the error log. I am using a combination of hydra and submit it and I am noticing some jobs end prematurely with no errors reported in either `<slurm_id>_log.err` or `<slurm_id>_log.txt`. The only indication that the job ended is the message like `submitit INFO (2021-07-29 00:56:05,771) - Job completed successfully`. 

Are there ways the jobs can be killed that aren't reported by slurm/submitit? or are there other logs that one can inspect or options to provide more context as to why the job failed? Also, my apologies if this is not a submitit issue. 

Thank you!

**Comment by jrapin** [comment]
`submitit INFO (2021-07-29 00:56:05,771) - Job completed successfully.` 
This does mean that the job completed as expected, what should it have done that it did not? Hydra may be catching an error somewhere and not raising it for submitit to handle.
Maybe you should load the result pickle manually to inspect what it contains?

**Comment by mbanani** [comment]
Thank you for the response. This is exactly what was happening. For reference, the pickled results were a tuple. The first element still said success, while the second element was a `hydra.core.utils.JobReturn` and its status attribute stated the failure and the `_return_value` attribute had the error.
