### ISSUE TITLE
Slurm job name with non alphanumeric symbols sanitized to underscores

### ISSUE THREAD

**Issue by piotrm-nvidia** [facebookincubator/submitit#1658]
Submitit is not able to start a job with a name containing non alphanumeric symbols e.g _project-subproject:test1_. If user pass such name it is changed to _project_subproject_test1_.

It is possible to configure a slurm cluster to force an user to add non alphanumeric symbols in a job name. Big clusters require such features for better allocation of resources to different projects.

## Reproduction

Create python program to run jobs with colon and run it:
```
user@cluster-head-node: ./colon_job_executor.py --job_name project-subproject:test1
```
Expected result
The job _project-subproject:test1_ is executed at cluster.

Actual results:

The executed job name is _project_subproject_test1_

```
2021-10-21 04:26:02,340 INFO The job project-subproject:test1 executed
sbatch: error: Please set a name for this job, formatted like this:
sbatch: error:  project-<subproject>:*
sbatch: error: Batch job submission failed: Access/permission denied
subprocess.CalledProcessError: Command '['sbatch', './file_job.sh']' returned non-zero exit status 1.
```
## Root cause

The __make_sbatch_string_ function in _slurm.py_ applies utils.sanitize to job_name without _only_alphanum_ argument set to false.

https://github.com/facebookincubator/submitit/blob/main/submitit/slurm/slurm.py#L463

```
    parameters["signal"] = f"USR1@{signal_delay_s}"
    if job_name:
        parameters["job_name"] = utils.sanitize(job_name) #Line 463 - sanitize replaces "-" and ":" with "_"
    if comment:
        parameters["comment"] = utils.sanitize(comment, only_alphanum=False)
    if num_gpus is not None:
        warnings.warn(
            '"num_gpus" is deprecated, please use "gpus_per_node" instead (overwritting with num_gpus)'
        )
        parameters["gpus_per_node"] = parameters.pop("num_gpus", 0)
```

## Solution

The solution can be changing line 463:

```
    if job_name:
        parameters["job_name"] = utils.sanitize(job_name, only_alphanum=False) 
    if comment:
```

**Comment by gwenzek** [comment]
IIUC the problem is that not all cluster accepts ":" in job names.
won't your proposed changes induce breakage for this clusters ?
don't you have better way to pass project information ? `wc_key` or `comment` come to mind.

**Comment by piotrm-nvidia** [comment]
Some clusters require colon some can't accept it. The point is that user should be able to set this behavior in some way. Today I pass job name with colon and it changes to "_".  I can't use submitit at my cluster without asking all users to pull my version of slurm.py.
