### ISSUE TITLE
sbatch: error: Batch job submission failed: Socket timed out on send/recv operation

### ISSUE THREAD

**Issue by slerman12** [facebookincubator/submitit#1659]
I think I'm getting this error because too many sbatch jobs are submitted too fast consecutively. Is there a way to slow down the rate that jobs are submitted? (unless this error means something else; please let me know)

**Comment by gwenzek** [comment]
this happens when the SLURM scheduler is overloaded.
You can throttle on your side, right now we haven't implemented a global submission throttling in `submitit`
Using job arrays also help by reducing the number of individual submissions.
