### ISSUE TITLE
Support the "account" parameter

### ISSUE THREAD

**Issue by kikohs** [facebookincubator/submitit#1665]
Hello,
Our cluster may require the `account`  and `reservation` parameters when launching jobs but it is not supported by submitit.
It would be great if they could be added.

Link: https://slurm.schedmd.com/sbatch.html#OPT_SBATCH_ACCOUNT
Thank you

**Comment by NormanTUD** [comment]
You may try to use `export SBATCH_ACCOUNT=account_name` and `export SBATCH_RESERVATION=reservation_name` around your python-script that uses submitit. This SHOULD (!) run them with the reservation/account, but please try.
