### ISSUE TITLE
filedescriptor out of range in select()

### ISSUE THREAD

**Issue by timlacroix** [facebookincubator/submitit#1687]
Got this traceback 
```
submitit/core/utils.py", line 260, in copy_process_streams
   ready, _, _ = select.select(fds, [], [])
ValueError: filedescriptor out of range in select()
```

select is limited to 1024 file descriptors. This is inconvenient if one wants to launch jobs in a program that already has lots of fds open.

**Comment by gwenzek** [comment]
Thanks for the PR.
