### ISSUE TITLE
Latest versions' tags not on Github

### ISSUE THREAD

**Issue by tmct** [facebookincubator/submitit#1690]
Hi - there is no tag on this github repo for the latest pypi builds, e.g. `1.4.3` - is there a way I can find which commit corresponds to which release please?

Thanks

**Comment by gwenzek** [comment]
sorry I did to forgot to push the last tag which is 1.4.2. Fixed.
I'll try to automate this with #1691

**Comment by tmct** [comment]
No problem - thanks very much!
