### ISSUE TITLE
NodeList Declaration

### ISSUE THREAD

**Issue by Bontempogianpaolo1** [facebookincubator/submitit#1692]
Hi,
Is it possible to declare the nodeList somehow (especially on slurm)?

**Comment by patricklabatut** [comment]
`nodelist` is not explicitly supported by the Slurm executor (yet), but the options specified in the `additional_parameters` parameter are passthrough for Slurm (i.e. passed as is to `sbatch`). Here is a simple example:

```
executor = submitit.AutoExecutor(...)
executor.update_parameters(slurm_additional_parameters={“nodelist”: “i-will-only-run-on-this-node”})
```

**Comment by Bontempogianpaolo1** [comment]
thank you very much! It worked!
