### ISSUE TITLE
submitit.core.utils.FailedJobError: sbatch: error: Parameter --gres=gpu:1 no longer acceptable, please switch to --gpus=1

### ISSUE THREAD

**Issue by RoyAmoyal** [facebookincubator/submitit#1710]
Hey,

My university is using Slurm version 21.08.1 and I am trying to run ConvNext with the run_with_submitit.py given in the ConvNext repository.  https://github.com/facebookresearch/ConvNeXt/blob/main/run_with_submitit.py

how can I fix that? 

thanks!

**Comment by gwenzek** [comment]
you must be using an old version of submitit. Recent ones use --gpus not --gres.
