### ISSUE TITLE
Can submitit manage chain dependencies?

### ISSUE THREAD

**Issue by eserie** [facebookincubator/submitit#1723]
Hi, thanks for this awesome project!

I started to write something similar but then realized that `submitit` exists and is much more advanced than my small project!

However, I realized that the chain dependency (as it is implemented in [dask.distributed](https://examples.dask.org/futures.html#Chain-dependencies)) seems missing in `submitit`.

Would it make sense to implement it? Or maybe it's already there?

It should be quite easy to implement by using the f `sbatch` option  `--dependency`.

**Comment by gwenzek** [comment]
submitit way of doing dependency is the following:

```py
ex = submitit.AutoExecutor("log/")
job1 = ex.submit(task1)
job1.wait()
job2 = ex.submit(task2)
```

if you want to you can also pass a "dependency" flag to sbatch or any other non supported flag using `ex.update_parameters(additional_parameters={"dependency": ...})`
