### ISSUE TITLE
duplicate tasks when using `SlurmExecutor.map_array`

### ISSUE THREAD

**Issue by eringrant** [facebookincubator/submitit#1727]
Thanks a lot for this library!

I'm using `SlurmExecutor.map_array` on a SLURM cluster. Each of my jobs has one associated task (

`first_job.num_tasks == 1` at https://github.com/facebookincubator/submitit/blob/4cf1462d7216f9dcc530daeb703ce07c37cf9d72/submitit/slurm/slurm.py#L333

), but when launched I see evidence of duplicate tasks for a subset of array jobs. For example, the folder for a job with SLURM job ID 3274571 has the following contents:

```bash
$ tree ...
├── 3274571
│   └── 3274571_submission.sh
├── 3274571_0
│   ├── 3274571_0_0_log.err
│   ├── 3274571_0_0_log.out
│   └── 3274571_0_submitted.pkl
├── 3274571_1
│   ├── 3274571_1_0_log.err
│   ├── 3274571_1_0_log.out
│   └── 3274571_1_submitted.pkl
├── 3274571_10
│   ├── 3274571_10_0_log.err
│   ├── 3274571_10_0_log.out
│   ├── 3274571_10_1_log.err
│   ├── 3274571_10_1_log.out
│   └── 3274571_10_submitted.pkl
.
.
.
```

Is this expected behavior that I missed the documentation for, or perhaps a bug? The jobs that generate duplicate tasks are unpredictable (and unrelated to job errors), so it is difficult to come up with a minimal reproduction.

**Comment by gwenzek** [comment]
can you share the content of "submission.sh" file ?

**Comment by eringrant** [comment]
Sure! Here's what the auto-generated `submission.sh` file looks like, where I've replaced some directories with `/path/to/log_dir/` and `/path/to/conda_env/`:

```
#!/bin/bash

# Parameters
#SBATCH --array=0-431%256
#SBATCH --cpus-per-task=1
#SBATCH --error=/path/to/log_dir/%A_%a/%A_%a_0_log.err
#SBATCH --gpus-per-node=1
#SBATCH --job-name=submitit
#SBATCH --mem=16GB
#SBATCH --nodes=1
#SBATCH --open-mode=append
#SBATCH --output=/path/to/log_dir/%A_%a/%A_%a_0_log.out
#SBATCH --partition=gpu
#SBATCH --signal=USR2@90
#SBATCH --time=480
#SBATCH --wckey=submitit

# command
export SUBMITIT_EXECUTOR=slurm
srun --unbuffered --output /path/to/log_dir/%A_%a/%A_%a_%t_log.out --error /path/to/log_dir/%A_%a/%A_%a_%t_log.err /path/to/conda_env/bin/python -u -m submitit.core._submit /path/log_dir/%j
```

**Comment by eringrant** [comment]
I now believe this occurs because the command passed from `submitit` to SLURM is underspecified.

[A StackOverflow answer](https://stackoverflow.com/a/58645583) addressing a similar case to mine suggested additionally passing `--exclusive --cpus-per-task=1 --ntasks=1` to `srun`. This also succeeds in getting rid of my task duplication: I now no longer see stdout/stderr from two tasks in each array job, and I'm able to allocate the entire GPU for a task on each node (whereas previously, I was getting OOM errors as the duplicate tasks attempt to simultaneously allocate GPU memory).

I've made this modification to the `srun` command in a fork of `submitit` here: https://github.com/eringrant/submitit/commit/b6105e3b2d78bd01e722d7f37ffb793b3bbc83ee. I haven't made this pull request as I'm not certain of whether there are side effects. However, I'm open to contributing this if someone with more knowledge of SLURM can review a PR.
