### ISSUE TITLE
Using `RsyncSnapshot` with a editable package install

### ISSUE THREAD

**Issue by jc-audet** [facebookincubator/submitit#1763]
Hey! Thanks for the great repo!

A little while back we set up an `RsyncSnapshot` block in our job submission in order to avoid having to deal with code changes at job preemption, but we quickly realized that code changes were affecting our jobs.

We think the issue is caused by our experiment repo is installed as an editable package in pip, which causes the function imported from the editable install to always point to the original code source and not the snapshot.
```
from project.train import main
with RsyncSnapshot(snapshot_dir=submitit_snapshot_path):
    executor = SlurmAccelerateExecutor(folder=submitit_logpath)
    executor.update_parameters(**asdict(executor_params))
    job = executor.submit(main, run_config, metadata)
logger.info(f"Job {job} submitted!")
```

When running a job in the rsyncsnapshot block, the working directory of the job is as expected, i.e., 
```
os.getcwd() == .../id_0819a821e056b1a06989a9eca1e5a4c875e141f04c226c36cd81fe99/snapshot/2024-02-19-23-32-51
```
, but the path of the function definition is pointed at the original code source.
```
os.path.abspath(inspect.getfile(fun)) == /home/jcaudet/...
```

This issue can be resolved by running `subprocess.run('pip install -e .', shell=True)` from within the rsync block, however this messes up the environment for other jobs also. Is there a better solution to this, or perhaps I'm not using this block as intended?

Thank you in advance!

**Comment by mshvartsman** [comment]
Naively, I'm not sure how this can be worked around. Say I have a conda env `foo` with editable package `bar1`. If we want to have multiple slurm jobs each using `foo` but with packages `bar1`, `bar2`, `bar3`, that's asking for code using the same conda env to use different versions of the same package, which seems to me to violate a basic contract of envs (same env == same set of requirements). 

There could be hacks around this but probably they would be outside the python package system. I think the best we can do on the submitit side is warn if running from an editable package? But not sure if that is possible.

**Comment by jc-audet** [comment]
Solution ended up being to modify the PYTHONPATH to include the editable packages from within the rsyncsnapshot like so:
```
####################
# Launch job
with RsyncSnapshot(snapshot_dir=submitit_snapshot_path):
    # Setting the PYTHONPATH to include the snapshot src folder
    # This is needed to actually use the code from the snapshot
    # otherwise it will use the code from the change-exposed folder
    # because of the editable installation of arrival_ssl,
    # arrival_data and fairseq2
    # Note: PYTHONPATH parses multiple paths given with `:` char
    # So here we are actually bypassing our three editable packages
    # with snapshot/src + snapshot/arrival_data/src + snapshot/fairseq2/src
    cwd = os.getcwd()
    os.environ[
        "PYTHONPATH"
    ] = f"{cwd}/src:{cwd}/some_submodule/src"
    executor = SlurmAccelerateExecutor(folder=submitit_logpath)
    executor.update_parameters(**asdict(executor_params))
    job = executor.submit(main, config, mode)
```
