### ISSUE TITLE
Set additional slurm parameters

### ISSUE THREAD

**Issue by netw0rkf10w** [facebookincubator/submitit#23]
Hello,

I would like to know if it's possible to set additional slurm parameters (and how to set them), because I couldn't find this information in the documentation.

For example, I have a few arguments that I usually set using `srun`, such as `--account=myaccount --hint=nomultithread --distribution=block:block --exclusive`, but I have no idea how to set them in `submitit`.

Thank you in advance for your answer!

**Comment by gwenzek** [comment]
There is some documentation in https://github.com/facebookincubator/submitit/blob/master/docs/examples.md#explained-example---initial-add-exemple-with-a-few-more-comments

It probably should be made more visible.

```py
executor = submitit.AutoExecutor(folder=log_folder)
# Cluster specific options must be appended to the cluster name:
# Eg.: slurm partition can be specified using `slurm_partition` argument. It
# will be ignored on other clusters:
executor.update_parameters(timeout_min=4, slurm_partition="dev")
```

so in your case it would be:

```py
executor.update_parameters(timeout_min=4, slurm_account="myaccount", slurm_hint="nomultithread", slurm_distribution="block:block",  slurm_exclusive=True)
```

**Comment by netw0rkf10w** [comment]
@gwenzek Thanks a lot for your answer!

**Comment by netw0rkf10w** [comment]
@gwenzek Unfortunately that doesn't work:


> NameError: Unknown argument 'account' for executor 'slurm' in parameter 'slurm_account'. Valid arguments: setup, ntasks_per_node, mem, gres, wckey, exclusive, cpus_per_task, gpus_per_task, nodes, num_gpus, partition, time, gpus_per_node, constraint, additional_parameters, signal_delay_s, exclude, job_name, comment, cpus_per_gpu, array_parallelism
> Unknown argument 'hint' for executor 'slurm' in parameter 'slurm_hint'. Valid arguments: setup, ntasks_per_node, mem, gres, wckey, exclusive, cpus_per_task, gpus_per_task, nodes, num_gpus, partition, time, gpus_per_node, constraint, additional_parameters, signal_delay_s, exclude, job_name, comment, cpus_per_gpu, array_parallelism
> Unknown argument 'distribution' for executor 'slurm' in parameter 'slurm_distribution'. Valid arguments: setup, ntasks_per_node, mem, gres, wckey, exclusive, cpus_per_task, gpus_per_task, nodes, num_gpus, partition, time, gpus_per_node, constraint, additional_parameters, signal_delay_s, exclude, job_name, comment, cpus_per_gpu, array_parallelism
> Known executors: slurm, local, debug

**Comment by netw0rkf10w** [comment]
The following works:

```python
executor.update_parameters(
    slurm_additional_parameters={
        'account': args.account,
        'hint': 'nomultithread',
        'distribution': 'block:block',
        'exclusive': True} 
)
```

**Comment by gwenzek** [comment]
sorry, I forgot we had that.

The thing is that slurm has too many flags, so in the end we ended up just adding a dictionary for arguments we don't support, to be sure to cover everyone usecase.
"account" sounds something we should support though.

**Comment by netw0rkf10w** [comment]
@gwenzek Thanks. The `slurm_additional_parameters` argument does the job nicely 👍
