### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pavelbatyr** [facebookincubator/submitit#24]
pip install submitit
```
Collecting submitit
  Downloading https://files.pythonhosted.org/packages/3d/7a/af94dc7bb279f84346419b1b0a036479878fe97b0e2913369f18d4bf5880/submitit-1.1.1.tar.gz (66kB)
    100% |################################| 71kB 205kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kktwvkje/submitit/setup.py", line 30, in <module>
        long_description=Path("README.md").read_text(),
      File "/usr/lib/python3.6/pathlib.py", line 1197, in read_text
        return f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5686: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kktwvkje/submitit/
```
Fixed it by changing this line in setup.py
`long_description=Path("README.md").read_text(),`
to
`long_description=Path("README.md").read_text(encoding='utf-8'),`

**Comment by pavelbatyr** [comment]
Python 3.6.9
Ubuntu 18.04.3 LTS bionic, it's a Docker container

`python -c 'import locale; print(locale.getpreferredencoding(False))'`
ANSI_X3.4-1968

`python -c 'import locale; print(locale.getdefaultlocale())'`
(None, None)
`locale -a`
C
C.UTF-8
POSIX

So yes, apparently my locale is not set up right.

**Comment by gwenzek** [comment]
Thanks for the details.
I think I'll still add the explicit encoding into the setup.py file, it doesn't seems right to have the installation fail because of the user preferred encoding.

Btw @jrapin this is due to your first name appearing in the Readme,
you can add that to the list of bugs caused by your poor choice of name :-p

**Comment by jrapin** [comment]
> Btw @jrapin this is due to your first name appearing in the Readme,
> you can add that to the list of bugs caused by your poor choice of name :-p

loool I didnt expect that :D
