### ISSUE TITLE
Cloudpick Cannot Pickle Weakref Objects with SQLAlchemy

### ISSUE THREAD

**Issue by Queuecumber** [facebookincubator/submitit#28]
Hi guys

I having an issue when I'm trying to use the SQLAlchemy ORM, I'm seeing if I can put together a minimal example that fails, but I'm not sure exactly what submitit is trying to pickle that is causing the problem. The relevant part of thee traceback is:

```
...
File "/private/home/mehrlich/submitit/submitit/core/core.py", line 606, in submit
    return self._internal_process_submissions([ds])[0]
  File "/private/home/mehrlich/submitit/submitit/slurm/slurm.py", line 314, in _internal_process_submissions
    return super()._internal_process_submissions(delayed_submissions)
  File "/private/home/mehrlich/submitit/submitit/core/core.py", line 726, in _internal_process_submissions
    delayed.dump(pickle_path)
  File "/private/home/mehrlich/submitit/submitit/core/utils.py", line 131, in dump
    cloudpickle_dump(self, filepath)
  File "/private/home/mehrlich/submitit/submitit/core/utils.py", line 283, in cloudpickle_dump
    cloudpickle.dump(obj, ofile, pickle.HIGHEST_PROTOCOL)
...
TypeError: can't pickle weakref objects
```

and I've narrowed it down the the following class:

```
class Result(Base):
    __tablename__ = "results"

    model = Column(String, primary_key=True)
    dataset = Column(String, primary_key=True)
    quality = Column(Integer, primary_key=True)
    mitigation = Column(String, primary_key=True)
    metric_key = Column(String)
    metric_value = Column(Float)

    def __repr__(self):
        return f"<Result(model_name='{self.model}', dataset='{self.dataset}', quality='{self.quality}', mitigation='{self.mitigation}', metric_key='{self.metric_key}', metric_value='{self.metric_value}')>"
```

which is defined at module scope. I can get the job to run under three conditions:

1. Removing this class definition
2. Removing the inheritance from `Base` (which comes from SQLAlchemy)
3. Removing any references in the function that I'm submitting to the `Result` class

I also tried moving the class definition from module scope to a function that returns the class which I run from the submitted function and it still fails with the same error.

Do you guys have any idea what might be happening?

**Comment by gwenzek** [comment]
So not everything can be pickled.
We use cloudpickle instead of the standard pickle because it's more flexible and support more things, but it doesn't seem to support [weakref](https://docs.python.org/3/library/weakref.html?highlight=weakref).

There was an old pull request for this on cloudpickle side: https://github.com/cloudpipe/cloudpickle/pull/67

I added a test to reproduce this: 4d096f4f0493a3253b263ac792d7b7ae6021a841

With weakref you'll need to copy the underlying data anyway.
Could you try to patch your object by looking at its attribute that are weakref and replace them by their pointee ?

**Comment by Queuecumber** [comment]
The `Result` object there is unfortunately very opaque and in a format that is required by SQLAlchemy, its possible that I could figure out a way to patch it that works but I'm not sure how to go about it. The thing that confused me is that I found some references to people using cloudpickle w/ SQLAlchemy, but it may have been in another context.

I replaced SQLAlchemy with Pony ORM and that seems to be working so far, so I'm going to go ahead and close

**Comment by gwenzek** [comment]
Generally the good strategy when dealing with unpicklable object is to create them inside your job.
So instead of doing:

```py
unpicklable = factory(x)
ex.submit(f, unpickable)
```

You do:

```py
def  g(x):
    unpicklable = factory(x)
    return f(unpickable)

ex.submit(g, x)
```

**Comment by Queuecumber** [comment]
yeah I tried that, it still had the same exception, it seems like the presence of that class is the problem
